# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DePoint' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'YYKit'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'WMPageController'
    pod 'BlocksKit'
    pod 'CocoaLumberjack'
    pod 'MLTransition' #解决自定义导航栏返回按钮后，手势右划返回失效的问题
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    
    pod 'hpple'
    pod 'RESideMenu'
    
    pod 'UMengAnalytics-NO-IDFA' #友盟数据统计 无IDFA
    
    #pod 'AMap3DMap' #3D地图SDK
    #pod 'AMap2DMap' #2D地图SDK(2D地图和3D地图不能同时使用)
    pod 'AMapSearch' #搜索服务SDK
    
    pod 'BmobSDK' #后台数据存储
    
    
    # Mob 分享
    # 主模块(必须)
    pod 'ShareSDK3'
    # Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
    #    pod 'MOBFoundation'
    pod 'MOBFoundation_IDFA'
    # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
    pod 'ShareSDK3/ShareSDKUI'
    # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    #pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    
    # 短信SDK
    pod 'SMSSDK'
end
